<a href="https://colab.research.google.com/github/shivpandey2406/Machine-Learning-Project/blob/main/SVC%20using%20different%20kernel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import  libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the data

In [5]:
dataset = pd.read_csv('/content/Social_Network_ads.csv')
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

## We do not necessarily need all the columns to make an analysis. So we will take only the age and salary column as the feature values.

In [8]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values
#X
#y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

## Now we will split the data into training and testing. We will take 75% of the data for training and test it on the rest which makes 25%.

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## After splitting, we will scale the feature to expect normal distribution of the data. We will use Standard Scaler in this case.

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358],
       [ 1.47293972,  0.99784738],
       [ 0.08648817, -0.79972756],
       [-0.01254409, -0.24885782],
       [-0.21060859, -0.5677824 ],
       [-0.21060859, -0.19087153],
       [-0.30964085, -1.29261101],
       [-0.30964085, -0.5677824 ],
       [ 0.38358493,  0.09905991],
       [ 0.8787462 , -0.59677555],
       [ 2.06713324, -1.17663843],
       [ 1.07681071, -0.13288524],
       [ 0.68068169,  1.78066227],
       [-0.70576986,  0.56295021],
       [ 0.77971394,  0.35999821],
       [ 0.8787462 , -0.53878926],
       [-1.20093113, -1.58254245],
       [ 2.1661655 ,  0.93986109],
       [-0.01254409,  1.22979253],
       [ 0.18552042,  1.08482681],
       [ 0.38358493, -0.48080297],
       [-0.30964085, -0.30684411],
       [ 0.97777845, -0.8287207 ],
       [ 0.97777845,  1.8676417 ],
       [-0.01254409,

## We will apply three kernel tricks in this case and try evaluating them.

In [12]:
from sklearn.svm import SVC

## Model for linear kernel

In [13]:
classifier_linear = SVC (kernel = 'linear', random_state = 0)
classifier_linear.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Predict our test data.

In [23]:
y_pred_linear = classifier.predict(X_test)
y_pred_linear

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

## Polynomial kernel

In [26]:
classifier_poly= SVC (kernel = 'poly', random_state = 0)
classifier_poly.fit(X_train, y_train)
y_pred_poly = classifier_poly.predict(X_test)
y_pred_poly

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

## RBF kernel

In [29]:
classifier_rbf= SVC (kernel = 'rbf', random_state = 0)
classifier_rbf.fit(X_train, y_train)
y_pred_rbf= classifier_rbf.predict(X_test)
y_pred_rbf

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

## The performance will be evaluated on the basis of confusion matrix and classification report.

In [30]:
from sklearn.metrics import confusion_matrix

## Confusion matrix for linear kernel

In [32]:
cm_linear = confusion_matrix(y_test, y_pred_linear)
cm_linear

array([[66,  2],
       [ 8, 24]])

## Confusion matrix for polynomial kernel

In [34]:
cm_poly=confusion_matrix(y_test,y_pred_poly)
cm_poly

array([[67,  1],
       [13, 19]])

## Confusion matrix for RBF kernel

In [35]:
cm_rbf=confusion_matrix(y_test,y_pred_rbf)
cm_rbf

array([[64,  4],
       [ 3, 29]])

If we evaluate the model based on the confusion matrix, then we can conclude that the model with the RBF kernel gave us the best result.

## Classification report
Classification report is an extended metric of confusion matrix which gives an idea about precision and recall. It tells us how well our model is and the exact accuracy of our model.

## Classification report on linear kernel

In [42]:
from sklearn.metrics import classification_report

In [43]:
class_report_linear = classification_report(y_test, y_pred_linear)
class_report_linear

'              precision    recall  f1-score   support\n\n           0       0.89      0.97      0.93        68\n           1       0.92      0.75      0.83        32\n\n    accuracy                           0.90       100\n   macro avg       0.91      0.86      0.88       100\nweighted avg       0.90      0.90      0.90       100\n'

## Classification report on poly kernel

In [45]:
class_report_poly = classification_report(y_test,y_pred_poly)
class_report_poly

'              precision    recall  f1-score   support\n\n           0       0.84      0.99      0.91        68\n           1       0.95      0.59      0.73        32\n\n    accuracy                           0.86       100\n   macro avg       0.89      0.79      0.82       100\nweighted avg       0.87      0.86      0.85       100\n'

## Classification report on RBF kernel

In [46]:
class_report_rbf = classification_report(y_test,y_pred_poly)
class_report_rbf

'              precision    recall  f1-score   support\n\n           0       0.84      0.99      0.91        68\n           1       0.95      0.59      0.73        32\n\n    accuracy                           0.86       100\n   macro avg       0.89      0.79      0.82       100\nweighted avg       0.87      0.86      0.85       100\n'

**Even after evaluating based on the classification report, the F1-score seems to be higher in the model with the RBF kernel compared with the other two models. So, the model with the RBF kernel seems to be the winner. But it still depends on the data handling and preprocessing to take an early call.**