<a href="https://colab.research.google.com/github/shivpandey2406/Machine-Learning-Project/blob/main/Using_GridSearchCV_find_beat_hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/shivpandey2406/Machine-Learning-Project.git

Cloning into 'Machine-Learning-Project'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 53 (delta 17), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (53/53), 2.33 MiB | 9.61 MiB/s, done.
Resolving deltas: 100% (17/17), done.


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Use GridSearchCV and select the best hyperparamter for Support Vector machine

In [9]:
df = pd.read_csv('/content/Machine-Learning-Project/Advertising_data.csv')
X = df.iloc[:,[2,3]].values
y = df.iloc[:,4].values




In [10]:
df.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [14]:
# Splitting the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=5)
#X_train

In [18]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
# Fitting kernel SVM to the training set
from sklearn.svm import SVC
clf = SVC(kernel= 'linear',random_state = 0)
clf.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [22]:
## Predicting the test set results
y_pred = clf.predict(X_test)
#y_pred

In [24]:
# Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[60,  6],
       [ 9, 25]])

In [25]:
## Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.85

## Applying Grid Search to find the best model and the best parameters

In [27]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = clf,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)


In [29]:
accuracy = grid_search.best_score_

accuracy

0.9100000000000001

In [30]:
## Display the best parameter values

grid_search.best_params_

{'C': 10, 'gamma': 0.3, 'kernel': 'rbf'}

In [34]:
## Now again implement it with this correct and best parameter values
clf = SVC(kernel= 'rbf',gamma = 0.3)
clf.fit(X_train, y_train)

SVC(gamma=0.3)

In [36]:
# Again predict the test set results
y_pred = clf.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [38]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[61,  5],
       [ 3, 31]])

In [39]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)


In [40]:
accuracy

0.92